# Configuration file for Travis-CI testing

language: node_js
node_js:
  - "0.8"
  - "0.10"
env:
  - MAPSERVER_COMMIT=rel-6-2-0  # v6.2.0
  - MAPSERVER_COMMIT=rel-6-2-1  # v6.2.1
  - MAPSERVER_COMMIT=rel-6-4-0  # v6.4.0
  - MAPSERVER_COMMIT=rel-6-4-1  # v6.4.1
  - MAPSERVER_COMMIT=           # repository HEAD
before_install:
  - sudo apt-get install libgif-dev                   # mapserver dependencies
  - sudo apt-get install lcov                         # enable code coverage
  - sh ./tools/install-deps.sh /tmp $MAPSERVER_COMMIT # install the dependencies
after_success:
  # Upload the code coverage data to coveralls
  - make coverage/node-mapserv.info
  - cat coverage/node-mapserv.info | ./node_modules/.bin/coveralls
