# Configuration file for Travis-CI testing
# Test using <http://lint.travis-ci.org/>

language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "0.13"
env:
  - MAPSERVER_COMMIT=rel-6-2-0  # v6.2.0
  - MAPSERVER_COMMIT=rel-6-2-1  # v6.2.1
  - MAPSERVER_COMMIT=rel-6-4-0  # v6.4.0
  - MAPSERVER_COMMIT=rel-6-4-1  # v6.4.1
  - MAPSERVER_COMMIT=           # repository HEAD
matrix:
  fast_finish: true
  # allow unstable versions to fail
  allow_failures:
    - node_js: "0.12"
    - node_js: "0.13"
    - env: MAPSERVER_COMMIT=
before_install:
  - sudo apt-get install libgif-dev                   # mapserver dependencies
  - sh ./tools/install-deps.sh /tmp $MAPSERVER_COMMIT # install the dependencies
